services:
    _defaults:
        autowire: true
        autoconfigure: false

    TM\RbacBundle\Command\:
        resource: '../../../Command'
        tags:
            - 'console.command'

    TM\RbacBundle\Command\InitializePermissionsCommand:
        arguments:
            $permissions: '%tm_rbac.permissions%'
        tags:
            - 'console.command'

    TM\RbacBundle\Repository\RepositoryProvider:
        arguments:
            $permissionModelClassName: '%tm_rbac.model.permission.class%'
            $roleModelClassName: '%tm_rbac.model.role.class%'
            $userModelClassName: '%tm_rbac.model.user.class%'

    TM\RbacBundle\EventListener\PermissionListener:
        arguments:
            $permissions: '%tm_rbac.permissions%'

    TM\RbacBundle\Form\Type\PermissionEntityChoiceType:
        arguments:
            $permissions: '%tm_rbac.model.permission.class%'
        tags:
            - 'form.type'

    TM\RbacBundle\Form\Type\RoleEntityChoiceType:
        arguments:
            $className: '%tm_rbac.model.role.class%'
        tags:
            - 'form.type'

    TM\RbacBundle\Security\Voter\PermissionVoter:
        arguments:
            $permissions: '%tm_rbac.permissions%'
        tags:
            - 'security.voter'

    TM\RbacBundle\Controller\:
        resource: '../../../Controller'
        tags:
            - 'controller.service_arguments'