TM\RbacBundle\Model\Role:
    type: mappedSuperclass
    fields:
        name:
            column: role_name
            type: string
            length: 255
            unique: true
        readOnly:
            column: read_only
            type: boolean
