TM\RbacBundle\Model\Role:
    table: tm_rbac_role
    type: entity
    repositoryClass: TM\RbacBundle\Repository\RoleRepository
    id:
        id:
            type: string
            generator:
                strategy: Uuid
    fields:
        name:
            column: role_name
            type: string
            length: 255
            unique: true
        readOnly:
            column: read_only
            type: boolean
    manyToMany:
        permissions:
            targetEntity: TM\RbacBundle\Model\Permission
            joinTable:
                name: tm_rbac_role_permissions
            joinColumns:
                role_id:
                    referencedColumnName: id
            inverseJoinColumns:
                permission_id:
                    referencedColumnName: id
