tm_rbac_permission_list:
    path: /
    methods: [GET]
    defaults:
        _controller: tm_rbac.controller.permission::listAction

tm_rbac_permission_read:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: tm_rbac.controller.permission::readAction

